kind: ConfigMap   
apiVersion: v1
metadata:
  name: backend
  namespace: expense      
data:
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # These labels for deployment resource. 
  labels:
    app: backend
    tier: backend
    purpose: expense
spec: 
  # Modify the replicas number according to our use case.
  replicas: 1
  selector:
  # Replicaset use these labels to find the pods for creating desired number of replicas.
    matchLabels:
      app: backend
      tier: backend
      purpose: expense
  # Pod Template
  template:
    metadata:
      labels: 
        app: backend
        tier: backend
        purpose: expense
    spec: 
      containers:
      - name: backend
        image: joindevops/backend:1.0.0   
        envFrom:
        - configMapRef:
            name: backend     
---
#Cluster IP
kind: Service
apiVersion: v1
metadata: 
  name: backend
  namespace: expense
spec: 
  selector: #Labels are used as seletors
     app: backend
     tier: backend
     purpose: expense
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080